pipeline {

    agent any

    environment {
        IMAGE = "mahmoudtarekjenkins/myapp:v1"
    }

    stages {


        stage('Build Docker Image') {

            steps {

                sh '''
                docker build -t $IMAGE .
                '''

            }
        }


        stage('Push Image to Docker Hub') {

            steps {

                sh '''
                docker push $IMAGE
                '''

            }
        }


        stage('Deploy with Ansible') {

            steps {

                sh '''
                ansible-playbook \
                -i ansible/inventory \
                ansible/docker-test.yml
                '''

            }
        }

    }

}
