---

- name: Download node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz


- name: Extract exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt
    remote_src: yes


- name: Create service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=node exporter

      [Service]
      ExecStart=/opt/node_exporter-1.8.1.linux-amd64/node_exporter

      [Install]
      WantedBy=multi-user.target


- name: Start exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
