global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "ec2-nodes"

    static_configs:

      - targets:

        - "44.211.33.184:9100"
        - "44.211.36.75:9100"
        - "3.238.253.58:9100"
