---
- name: Deploy my app
  hosts: inventory
  become: yes

  tasks:


    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Start service
      service:
        name: httpd
        state: started

