---

- name: Install docker
  yum:
    name: docker
    state: present


- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes


- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes


- name: Create docker cli plugin directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'


- name: Install docker compose plugin
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'
